name: Publish docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout lib with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pydoctor
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install docutils pydoctor

    - name: Generate docs
      run: |
        pydoctor \
            --project-name=tivars_lib_py \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --theme readthedocs \
            --make-html \
            --html-output=./docs \
            --project-base-dir="$(pwd)" \
            --docformat=restructuredtext \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./tivars

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/


  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
