name: Publish wiki

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Strip Markdown links
        uses: impresscms-dev/strip-markdown-extensions-from-links-action@v1.0.0
        with:
          path: wiki
      - name: Push to wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4