name: Publish wiki

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lib with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run build script
        run: |
          python wiki/build.py

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Strip Markdown links
        uses: impresscms-dev/strip-markdown-extensions-from-links-action@v1.0.0
        with:
          path: wiki
      - name: Push to wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4